### ISSUE TITLE
User added layers visibility toggle bug

### ISSUE THREAD

**Issue by yileifeng** [RCSideProjects/RAMP-Vue-Testing#17]
![visibilityBug ](https://user-images.githubusercontent.com/31557789/66598425-050ac580-eb6f-11e9-93f8-cbaefabd4d23.gif)

There is some strange behavior with the visibility toggle for user-added entries.

**Comment by RyanCoulsonCA** [comment]
Yeah, this is because right now the toggle properties are being added directly to the root object. This shouldn't be a problem once we have a state storage method (#7) and we can set default values for everything.

**Comment by RyanCoulsonCA** [comment]
Here's a gif of the toggle working with some sort of state management implemented:

![](https://i.imgur.com/Gc3zTJ7.gif)

**Comment by RyanCoulsonCA** [comment]
Fixed with #18.
