### ISSUE TITLE
Restrict to allow maximum of one table panel open at a time

### ISSUE THREAD

**Issue by yileifeng** [RCSideProjects/RAMP-Vue-Testing#49]
Currently, clicking on different layer entries will display its `GridComponent` regardless if there was a previously open table, causing many overlapping `GridComponents`. We want one table to be open at all times.

Along the same lines, implement functionality to close a table panel from the grid itself.

**Comment by RyanCoulsonCA** [comment]
#60 adds the ability to close a table panel from the grid.
