### ISSUE TITLE
Reordering columns improvement

### ISSUE THREAD

**Issue by yileifeng** [RCSideProjects/RAMP-Vue-Testing#51]
Reordering columns can remove the columns from the grid altogether: 

![gridMagic](https://user-images.githubusercontent.com/31557789/69433819-5b405c00-0d0a-11ea-8847-a94a70fdd491.gif)

**Comment by RyanCoulsonCA** [comment]
It looks like you can prevent dragging the columns out of the grid by adding the following line to the grid definition:
`:suppressDragLeaveHidesColumns="true"`

It gives you something like this:
![](https://i.imgur.com/ar1AyHS.gif)

**Comment by RyanCoulsonCA** [comment]
I've implemented the first solution for now.

My next step is to implement column reordering as it currently works in RAMP3. I'll add left and right arrows to the column headers and allow them to be swapped.
