### ISSUE TITLE
Implement table controls

### ISSUE THREAD

**Issue by yileifeng** [RCSideProjects/RAMP-Vue-Testing#53]
Implement some table controls that exist for the grid in RAMP3:

- [x] global search 
- [x] hide specified columns 
- [x] clear column filters
- [x] apply to map (N/A) 
- [x] table menu (split view, maximize, show/hide filters, print, export)
- [x] close table 

Not applicable to mobile view.

**Comment by RyanCoulsonCA** [comment]
#60 begins to implement some of these features.

**Comment by RyanCoulsonCA** [comment]
As of #67 all features have been completed except for apply to map. There isn't a map in our prototype, so adding this feature is not necessary at this time.
