### ISSUE TITLE
Find a method to effectively store layer state

### ISSUE THREAD

**Issue by RyanCoulsonCA** [RCSideProjects/RAMP-Vue-Testing#7]
As of right now, we're using a hard-coded object tree in `main.js` to hold the layer entries. Any time I want to add a property, I'm adding it directly to that object tree. It's not currently possible to efficiently access the parent of any given entry. Obviously this isn't going to fly, so we need to find a method to effectively store layers and their properties.

__Current method__
![bad](https://user-images.githubusercontent.com/25874602/66493169-8f75fb00-ea83-11e9-9617-be0d7f779ce8.png)

It isn't going to be possible to implement many of RAMP's features until we figure out how we want to do this, so any discussion is welcome 😄

**Comment by RyanCoulsonCA** [comment]
Here's a quick proposal --

We create a class called `LayerState` that stores all of the information for any given layer. We store the root `LayerState` node (the node that will hold all layers) in the Vuex store so that it can be accessed from anywhere within the application.

The `LayerState` class would include the properties `children` and `parent`, where `children` is a list of other `LayerState` objects, and `parent` is a link to the node's parent `LayerState` object. We will also include other properties in this class to maintain the state of the layer in other parts of the application (i.e., opacity).

This structure will allow us to access any node in a tree-like manner, and has added efficiency because we store the pointer to the parent node in the object. The tree structure also allows for easy propagation up and down the layers.

Here's a quick example of what the `LayerState` class could look like (minus proper documentation and TypeScript use):
![](https://i.imgur.com/jZxQXcp.png)

And here's an example of how we would store the root node in the Vuex store:
![](https://i.imgur.com/j1eMHq0.png)

**Comment by yileifeng** [comment]
Should `legendComponents` be an array of `LayerState` objects? This way you can add other legend entries on the same level as opposed to only adding to the root's children. Then adding a new layer would be creating a new `LayerState` object, which seems to make sense?

Aside from that, I think this is a good implementation to have for now to be able to get most of the basic legend functionality working first.

**Comment by RyanCoulsonCA** [comment]
@yileifeng Oh yeah good point, forgot to bring this up in the main post.

What I thought we'd do here is have the actual root not be displayed in the legend and only have it's children displayed. We gain a few things by doing this:

1. implementing methods that affect all layers (show/hide all, for example) is a lot easier because we can just apply it to the invisible root node and have it propagate down
2. there's a single source that we can refer to when we want to access the layers. Using an array would mean we'd need to use loops to find specific layers, which reduces efficiency, especially if there are a lot of layers at the top level.

By making the root node not show up in the legend, any layers added by the user would appear as "top-level" from the user perspective.

**Comment by RyanCoulsonCA** [comment]
#18 implements a basic version of this proposal. I'll leave this issue open so discussion can continue.

**Comment by RyanCoulsonCA** [comment]
In my attempts to implement the symbology stack, I've discovered another issue related to state storage.

As we know, the legend can contain different elements (text, images, layers, symbology stacks, visibility sets, etc.), and each of these elements have different properties associated with them.

Using my proposal as it is right now raises a problem: if we only use one class to represent any legend node, then we're going to have a bunch of unused properties in the class (i.e., a text entry isn't going to use `children`, `toggled`, `expanded`, etc.). As we add more and more properties and methods to `LayerState`, it's going to get more confusing to read if we keep all of the properties in this one class.

I've come up with two solutions to this problem, and feel free to recommend another solution or add to one of mine below:

**Solution 1** 
To keep `LayerState` more true to it's name, we only store _layer specific_ information in this class, such as opacity, visibility, and data points. We then create separate classes for each of the elements that store the element-specific properties. We pass in these separate classes as the "element" property into the components. The class we create to store layers will have an added property that points to it's LayerState object.

**Solution 2**
We make `LayerState` a high-level class, and create sub-classes for each element that extend `LayerState`. `LayerState` would include properties such as name and parent, and the sub-classes would contain the more element-specific properties.

For example, we do something like this:
```
class LayerState {
  constructor(name, ...) {
    this.name = name;
    ...
  }

  ...
}

class TextEntry extends LayerState {
  constructor(name, content, ...) {
    super(name);
    this.content = content;
    ...
  }

 ...
}
```
